name: build-and-push

on:
  schedule:
    - cron: '52 17 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check if there is a new base image
        if: github.event_name != 'push' && github.event_name != 'workflow_dispatch'
        id: check
        run: |
          set -Eeuxo pipefail
          sudo apt install -y curl jq skopeo
          PARENT=$(skopeo inspect docker://ubuntu:23.10 | jq .Layers)
          OWN=$(skopeo inspect docker://ghcr.io/nikarh/github-actions-runner | jq .Layers)
          OUTOFDATE=$(jq -cn "$OWN - ($OWN - $PARENT) | .==[]")
          echo "out-of-date=$OUTOFDATE" >> $GITHUB_OUTPUT
        
      - name: Checkout repository
        if: steps.check.outputs.out-of-date == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4

      - name: Build image
        if: steps.check.outputs.out-of-date == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: github-actions-runner
          tags: latest
          containerfiles: |
            ./Dockerfile

      - name: Push to ghcr.io
        if: steps.check.outputs.out-of-date == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io/nikarh
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
